### ISSUE TITLE
Javascript Test is failing

### ISSUE THREAD

**Issue by Hardwaregore** [Hardwaregore/insane-chess#17]
@TechDudie, what is this and why is it failing the javascript check????

![Screen Shot 2022-02-07 at 6 34 33 PM](https://user-images.githubusercontent.com/88296644/152895659-16dc4758-29aa-4720-a98f-14d31bcb4569.png)

**Comment by TechDudie** [comment]
Its stupid ok now leave it alone

**Comment by Hardwaregore** [comment]
@TechDudie 
can u plz fix ur code? EVERY SINGLE TIME I DO A COMMIT, I GET 10 EMAILS FROM GITHUB SAYING THAT IT FAILED YOUR STUPID TESTS!!!!!! fix it plz????? 
- from @Hardwaregore

**Comment by Hardwaregore** [comment]
@TechDudie @TechDudie @TechDudie  !!!!!!!
FIX YOUR CODE RIGHT NOW,  THE STUPID JAVASCRIPT CHECKS CRASHED MY MACBOOK!!!!!! I HAVE TO WRITE THIS COMMENT FROM MY PHONE!!!!
