### ISSUE TITLE
nav bar dosn't work

### ISSUE THREAD

**Issue by Hardwaregore** [Hardwaregore/Insane-chess#2]
in the beta testing branch, the navbar displays perfectly fine but in the main, the CSS doesn't work.

**Comment by Hardwaregore** [comment]
I am stupid. In the beta testing branch, I put Style.css for the link. The main branch has style.css. This caused things to not link correctly when I copy and paste the code from the branches. BRUH

**Comment by TechDudie** [comment]
lol

**Comment by TechDudie** [comment]
I corrected the stuff in the main branch, but you forked it before i corrected it
