### ISSUE TITLE
ms.kading is mad

### ISSUE THREAD

**Issue by TechDudie** [Hardwaregore/insane-chess#5]
https://github.com/Hardwaregore/insane-chess/blob/main/urbanned.php#L22

**Comment by SirAlexBigBrain** [comment]
LOL

**Comment by Hardwaregore** [comment]
@SirAlexBigBrain WAIT, UR ACTUALLY ON!!!!!

**Comment by TechDudie** [comment]
LOL me replying to your github message on a flip phone-- Sent from TechnoPhoneHardwaregore/insane-chess wrote:
@SirAlexBigBrain WAIT, UR ACTUALLY ON!!!!!

**Comment by TechDudie** [comment]
sent her this too

https://github.com/Hardwaregore/insane-chess/blob/main/urbanned.php#L103

**Comment by TechDudie** [comment]
reault? I think thats a reault of your bad spelling lol

im replying to everything in like 10 mins
