### ISSUE TITLE
a u t h e n i c a t i o n

### ISSUE THREAD

**Issue by TechDudie** [Hardwaregore/insane-chess#7]
okay im not an admin lemme unban myself i just need to send the correct HTTP response BECASUE ANY1 CAN

IT SHOULD BE A POST REQUEST WITH CREDIENTIALS IN IT LIKE I DID WITH GRASSBANDITS 
https://github.com/TechDudie/GrassBandits/blob/main/app.py#L51

or i can set my username to <script>alert("never gonna give you up");</script> i dare you ban me

USER INPUT SANITIZATION TO AVOID XSS I THOUGHT YOU WERE GOOD AT PHP

**Comment by Hardwaregore** [comment]
I JUST HAD MAP TESTING! GIMMIE A BREAK!!!

**Comment by TechDudie** [comment]
coding never takes breaks why am i still coding i *totally did not* get minecraft on school mac now im working on unblocking websites like fandom.com minecraft section for example

did siralexbigbrain not tell u?

**Comment by Hardwaregore** [comment]
Blue valley gives our chrome books that are based on BSD not UNIX like ur macs. They have the shell disabled and you can’t even change ur wallpaper. You also can’t download any files. USB drives are also disabled. They even blocked the rickroll! That’s why I have to rely on my LoadMaster for unblocking. Also, I get a crap ton of HW so…….

**Comment by TechDudie** [comment]
> Blue valley gives us chrome books that are based on BSD not UNIX like ur macs. They have the shell disabled and you can’t even change ur wallpaper. You also can’t download any files. USB drives are also disabled. They even blocked the rickroll! That’s why I have to rely on my LoadMaster for unblocking. Also, I get a crap ton of HW so…….

bruh.

**Comment by TechDudie** [comment]
@SirAlexBigBrain

**Comment by TechDudie** [comment]
> > Blue valley gives us chrome books that are based on BSD not UNIX like ur macs. They have the shell disabled and you can’t even change ur wallpaper. You also can’t download any files. USB drives are also disabled. They even blocked the rickroll! That’s why I have to rely on my LoadMaster for unblocking. Also, I get a crap ton of HW so…….
> 
> bruh.

simple: get a screwdriver and a ssd to usb converter and plug it in WINDOEZ computer (so you can see all the files without any shell and linuxy interference) and uh... you can see where im going

chrome os isnt exactly that protected

**Comment by TechDudie** [comment]
wait a minute did the school block the shell or does it not exist? because i got the shell on peters cromebook

**Comment by TechDudie** [comment]
macos has encwyption :( feel grateful

i get stuff by taking apart the package manually and combing through nesesary filez and do some file surgury
after that i run some commwands to override the Unindentified Developer (right click open doesnt work)
`pkgutil --expand-full WahteverIWant.pkg`
`xattr -d com.apple.quarantine WhateverIWant.app`

**Comment by TechDudie** [comment]
nodejs, eclipse, java, minecwaft, audacity, spotify, technostore?

This comment is sponsored by... TechnoStore! TechnoStore is a free online marketplace for unblocked games to play! Just paste in the app ID into TechnoInstaller, enter your administrators (me) encryption code, and BOOM! You've installed it! Scratch may get blocked at some point, but not to worry! Our scratch games have been compiled to JavaScript so they run much smoother... and they are stored locally so EVERYTHING still works even in scratch is blocked! Tons (okay 2 atm) of games are available to play! Just visit https://techdudie.github.com/TechnoStore ! Enjoy!

**Comment by Hardwaregore** [comment]
when i open the shell, it saids that "terminal been disabled by administrator"

**Comment by TechDudie** [comment]
Windoez ignorez mac/linux filesys blockerzcwomebook isnt encwypted i think so plug the hard drive in and have *fun*-- Sent from TechnoPhoneHardwaregore/insane-chess wrote:
when i open the shell, it saids that "terminal been disabled by administrator"

**Comment by TechDudie** [comment]
appel education .plist file is stored in ~/library/apple education config/ folder... where i have acces 2 bruh hecking is so much ezer-- Sent from TechnoPhoneHardwaregore/insane-chess wrote:
when i open the shell, it saids that "terminal been disabled by administrator"

**Comment by Hardwaregore** [comment]
there is nothing stopping me from running `sudo rm -rf /*` on the imacs in the computer lab and there isnt anything stopping me from running `pkill -u $(whoami)` on the imacs either. Also, in high school, we get macbooks with the shell enables so....... also, imma smash my school chromebook the milisecond we graduate middle school because you are allowed to break 1 school computer before they make you pay for ur 3rd computer....................
